### ISSUE TITLE
How to get different makeup level? 

### ISSUE THREAD

**Issue by zzmao** [wtjiang98/PSGAN#10]
In the paper, looks like it is mentioned that the result can have different makeup heaviness. Is this implemented in current code version?

**Comment by wtjiang98** [comment]
It is not implemented yet. We will update the code soon.

**Comment by AaronSun2000** [comment]
Hi! Have the current version released yet? Can you please instruct how to change makeup heaviness to me? Thanks a lot! @wtjiang98
