### ISSUE TITLE
Smart_Path

### ISSUE THREAD

**Issue by testingdlrna** [wtjiang98/PSGAN#11]
Hello @wanzysky and @wtjiang98 ,
during the demo running I found this error:

from smart_path import smart_path
ModuleNotFoundError: No module named 'smart_path'

**Comment by wanzysky** [comment]
Thanks for noticing.

It is an unnecessary dependence of https://github.com/wanzysky/smart_path, and I have committed a fix.
Please update by pulling again or install smart_path from https://github.com/wanzysky/smart_path to use the current version of code.

Let me know here if you have any updates or other questions.

**Comment by testingdlrna** [comment]
@wanzysky Yes, I have pulled the code again and now it compiles perfectly. Another problem now occurs, basically, by passing two images the first as input and the second as reference (both included in non-makeup and makeup respectively) the demo.py doesn't return any image in the output.
