### ISSUE TITLE
Hi~I‘m trying to review your project，But the data set seems to be undownloadable.

### ISSUE THREAD

**Issue by yql0612** [wtjiang98/PSGAN#14]

**Comment by wanzysky** [comment]
Dataset is available at https://1drv.ms/u/s!AgqNJZCiLRDCgaYWgH5Pe5ppH3qc4w?e=jCnods

**Comment by yql0612** [comment]
您好，我之前解压您发的数据集后发现landmark和segment里面的图片都是像我截图这样的，并没有标记和分割，请问是哪里出问题了呢？








------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Zhaoyi Wan 万昭祎"<notifications@github.com&gt;; 
发送时间: 2020年7月24日(星期五) 下午4:24
收件人: "wtjiang98/PSGAN"<PSGAN@noreply.github.com&gt;; 
抄送: "1079578049"<1079578049@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [wtjiang98/PSGAN] Hi~I‘m trying to review your project，But the data set seems to be undownloadable. (#14)





 
Dataset is available at https://1drv.ms/u/s!AgqNJZCiLRDCgaYWgH5Pe5ppH3qc4w?e=jCnods

**Comment by yql0612** [comment]
Thanks a lot!!! I have download it, but when I open landmark and seg folder, I found all of pictures are black, and no any contents like these screenshots.  look forward to your reply~
![image](https://user-images.githubusercontent.com/50354727/88376373-d2654d00-cdcf-11ea-9d08-88b177d785e1.png)
![image](https://user-images.githubusercontent.com/50354727/88376481-15272500-cdd0-11ea-890f-e19c93f60e4e.png)

**Comment by wanzysky** [comment]
The files are not regular “.png” files in the conventional format, though using the same suffix for convenience. PLEASE check the code for details.

**Comment by SamuelSJTU** [comment]
> Dataset is available at https://1drv.ms/u/s!AgqNJZCiLRDCgaYWgH5Pe5ppH3qc4w?e=jCnods

The dataset seems unavailable in the link. Can you update the link? Thanks

**Comment by yql0612** [comment]
Still cant...




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Samuel Wang"<notifications@github.com&gt;; 
发送时间: 2020年8月13日(星期四) 下午4:24
收件人: "wtjiang98/PSGAN"<PSGAN@noreply.github.com&gt;; 
抄送: "1079578049"<1079578049@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [wtjiang98/PSGAN] Hi~I‘m trying to review your project，But the data set seems to be undownloadable. (#14)





  
Dataset is available at https://1drv.ms/u/s!AgqNJZCiLRDCgaYWgH5Pe5ppH3qc4w?e=jCnods
  
The dataset seems unavailable in the link. Can you update the link? Thanks

**Comment by wanzysky** [comment]
Hi there, I am sorry about this but have no idea why the link turns unavailable.

I shared the files again at https://1drv.ms/u/s!AgqNJZCiLRDCgaZD5Qa9x4-IX32CHg?e=01uw7C.

**Comment by yql0612** [comment]
yeah, it can download.

> Hi there, I am sorry about this but have no idea why the link turns unavailable.
> 
> I shared the files again at https://1drv.ms/u/s!AgqNJZCiLRDCgaZD5Qa9x4-IX32CHg?e=01uw7C.

**Comment by yql0612** [comment]
> Hi there, I am sorry about this but have no idea why the link turns unavailable.
> 
> I shared the files again at https://1drv.ms/u/s!AgqNJZCiLRDCgaZD5Qa9x4-IX32CHg?e=01uw7C.

hi~ I'm new to this field, I have some issues about training, G.pth in /assets/models, What does it do?  I see the codes solver.py have load it, but this folder doesn't include D_A.pth, D_B.pth, it'is necessary to train? I delete G.pth when I train this model, but results still looks good, only adv loss seems no change. sincerely look forward your detailed reply,Thanks.
![image](https://user-images.githubusercontent.com/50354727/90335122-f39f0f00-e004-11ea-96f2-341d35424515.png)

**Comment by wanzysky** [comment]
> > Hi there, I am sorry about this but have no idea why the link turns unavailable.
> > I shared the files again at https://1drv.ms/u/s!AgqNJZCiLRDCgaZD5Qa9x4-IX32CHg?e=01uw7C.
> 
> hi~ I'm new to this field, I have some issues about training, G.pth in /assets/models, What does it do? I see the codes solver.py have load it, but this folder doesn't include D_A.pth, D_B.pth, it'is necessary to train? I delete G.pth when I train this model, but results still looks good, only adv loss seems no change. sincerely look forward your detailed reply,Thanks.
> ![image](https://user-images.githubusercontent.com/50354727/90335122-f39f0f00-e004-11ea-96f2-341d35424515.png)

Please open a new issue if you have parallel questions. Your message will be deleted here.

**Comment by DanielMao2015** [comment]
@wanzysky The link is unavailable again.  Is there any chance for you to share the link again or the data can be downloaded through Baidu cloud disk?

**Comment by wtjiang98** [comment]
> @wanzysky The link is unavailable again. Is there any chance for you to share the link again or the data can be downloaded through Baidu cloud disk?

For BaiduYun users, you can download the data at https://pan.baidu.com/s/1ZF-DN9PvbBteOSfQodWnyw. Password: rtdd

**Comment by umarshehu** [comment]
wan

> The files are not regular “.png” files in the conventional format, though using the same suffix for convenience. PLEASE check the code for details.

Thanks. I checked code by cant find reference to how to create "PNG" files in landmarks and segs, please which folder has code?

**Comment by martin-etchart** [comment]
Hi there, I want to download the dataset also but cannot create a Baidu account from my country. Can you provide a new OneDrive link? Than you
