### ISSUE TITLE
生成的图片不太对

### ISSUE THREAD

**Issue by SeeU1119** [wtjiang98/PSGAN#15]
很麻烦再一次打扰您， 我按照readme的教程从头开始训练，迭代了一段时间，发现生成的fake_A总是将脸部变成黑色，请问一下，我是哪里出了什么问题，谢谢。
就比如下面所示：
![image](https://user-images.githubusercontent.com/38234791/89364765-cfd6f180-d705-11ea-9bae-8d0e3a460910.png)

还有我发现在得到weight使用稀疏张量会减慢模型训练速度，是否可以注释掉：
# weight = weight[weight_ind[0], weight_ind[1], weight_ind[2]]
# ret = torch.sparse.FloatTensor(weight_ind, weight, torch.Size([3, HW, HW]))
 y = torch.bmm(weight.to_dense(), g_source)--------> y = torch.bmm(weight, g_source)

**Comment by DanielXu123** [comment]
我也是。 只有0_0_fake,jpg 不是黑的 别的第三张 Generator的图面部全部都是黑色的

**Comment by wanzysky** [comment]
请使用pytorch 1.5

**Comment by SeeU1119** [comment]
谢谢您的回复， 我先去试试！

**Comment by DanielXu123** [comment]
![24_0_fake](https://user-images.githubusercontent.com/30657808/91830944-04db5300-ec76-11ea-9942-7a70759bb8b4.jpg)
![23_0_fake](https://user-images.githubusercontent.com/30657808/91830973-0d338e00-ec76-11ea-916a-c3c46c8d2b03.jpg)


使用2个GPU训练，Generator.pth 生成的图经常会有类似这样的问题，不知道是不是哪里的参数需要调整一下？

**Comment by aaronpetok** [comment]
> ![24_0_fake](https://user-images.githubusercontent.com/30657808/91830944-04db5300-ec76-11ea-9942-7a70759bb8b4.jpg)
> ![23_0_fake](https://user-images.githubusercontent.com/30657808/91830973-0d338e00-ec76-11ea-916a-c3c46c8d2b03.jpg)
> 
> 使用2个GPU训练，Generator.pth 生成的图经常会有类似这样的问题，不知道是不是哪里的参数需要调整一下？

请问您有发现问题在哪吗？我用一个gpu训练的，也是有这个问题，感觉妆容没有很好的迁移，只是整个图片的style变了一下。

**Comment by DanielXu123** [comment]
> > ![24_0_fake](https://user-images.githubusercontent.com/30657808/91830944-04db5300-ec76-11ea-9942-7a70759bb8b4.jpg)
> > ![23_0_fake](https://user-images.githubusercontent.com/30657808/91830973-0d338e00-ec76-11ea-916a-c3c46c8d2b03.jpg)
> > 使用2个GPU训练，Generator.pth 生成的图经常会有类似这样的问题，不知道是不是哪里的参数需要调整一下？
> 
> 请问您有发现问题在哪吗？我用一个gpu训练的，也是有这个问题，感觉妆容没有很好的迁移，只是整个图片的style变了一下。
 
暂时还没有继续尝试，不知道是不是batchsize的问题。基本上大浓妆的眼妆部分迁移的效果都很奇怪

**Comment by aprillysea** [comment]
> > > ![24_0_fake](https://user-images.githubusercontent.com/30657808/91830944-04db5300-ec76-11ea-9942-7a70759bb8b4.jpg)
> > > ![23_0_fake](https://user-images.githubusercontent.com/30657808/91830973-0d338e00-ec76-11ea-916a-c3c46c8d2b03.jpg)
> > > 使用2个GPU训练，Generator.pth 生成的图经常会有类似这样的问题，不知道是不是哪里的参数需要调整一下？
> > 
> > 
> > 请问您有发现问题在哪吗？我用一个gpu训练的，也是有这个问题，感觉妆容没有很好的迁移，只是整个图片的style变了一下。
> 
> 暂时还没有继续尝试，不知道是不是batchsize的问题。基本上大浓妆的眼妆部分迁移的效果都很奇怪

啊啊啊啊，我训练出来的也是这样，效果不好
