### ISSUE TITLE
Is it possible for higher resolution?

### ISSUE THREAD

**Issue by DanielMao2015** [wtjiang98/PSGAN#17]
The default resolution is 256. But if there exsisting dataset of high resoluiton such as 512, is it possilbe to train generator that can produce result of high resolution  when I change some config and hyperparameter in the code?

**Comment by wanzysky** [comment]
If you aim at training with higher resolution, the answer is currently no. Nevertheless, inference on high-resolution images is supported by Laplace transformation. Try demo with your customized dataset to check it.

**Comment by DanielMao2015** [comment]
@wanzysky Thanks for your reply!!  I am curious about the reason about the impossibility. As I know, if I change the input size, and modify the size of AMM  and other corresponding hyperparameter, why is it impossible to produce high resolution? By the way, I have no idea how to inference on high-resolution with Laplace transformation, it would be appreciated of you to provide some explanation or some links. Thank you !!

**Comment by wanzysky** [comment]
The main reason against the higher resolution is the limitation of GPU memory.  Laplace transformation has been implemented in psgan/postprocess.py. It is actually a direct idea to alleviate the distortion caused by bilinear interpolation.
