### ISSUE TITLE
Pre-trained models

### ISSUE THREAD

**Issue by yql0612** [wtjiang98/PSGAN#18]
hi~ I'm new to this field, I have some issues about training, G.pth in /assets/models, What does it do? I see the codes solver.py have load it, but this folder doesn't include D_A.pth, D_B.pth, it'is necessary to train? I delete G.pth when I train this model, but results still looks good, only adv loss seems no change. sincerely look forward your detailed reply,Thanks.
![image](https://user-images.githubusercontent.com/50354727/90350665-698c9000-e070-11ea-82a7-8d98662d5f4c.png)

**Comment by wanzysky** [comment]
Pre-trained models are not necessary for training.

**Comment by AloneGu** [comment]
BTW, how to choose the best G model from snapshots?

**Comment by wtjiang98** [comment]
> BTW, how to choose the best G model from snapshots?

Through qualitative evaluation.

**Comment by yql0612** [comment]
您的邮件我已收到。祝一切顺利！
