### ISSUE TITLE
the performance of demo

### ISSUE THREAD

**Issue by Zteat** [wtjiang98/PSGAN#21]
I tried to run the demo and used some other pictures from the Internet. The results i got are not as good as the paper showed. The eye shadow part cannot be transferred. Should i change the config or train the model by myself to get a better result?

**Comment by Hellboykun** [comment]
> 我尝试运行该演示并使用了Internet上的其他图片。我得到的结果不如论文所示。眼影部分无法转印。我应该自己更改配置还是自己训练模型以获得更好的结果？

hello，could you please share your demo code?thank you very much!
