### ISSUE TITLE
Download training dataset

### ISSUE THREAD

**Issue by DokhyamLT** [wtjiang98/PSGAN#23]
Hi, 
I tried to download the dataset in the link that was supplied but it appears that the file has either been removed or that I need some special authentication for it. How can I use this dataset?

**Comment by back-js** [comment]
me too

**Comment by wanzysky** [comment]
https://1drv.ms/u/s!AgqNJZCiLRDCgaZDG_lZxuSQa6X7UQ

**Comment by back-js** [comment]
> https://1drv.ms/u/s!AgqNJZCiLRDCgaZDG_lZxuSQa6X7UQ

thanks!! 
Your project is so impressive.

**Comment by DWCTOD** [comment]
> https://1drv.ms/u/s!AgqNJZCiLRDCgaZDG_lZxuSQa6X7UQ

Hi, this url does not exist

**Comment by AloneGu** [comment]
> > https://1drv.ms/u/s!AgqNJZCiLRDCgaZDG_lZxuSQa6X7UQ
> 
> Hi, this url does not exist

+1

**Comment by Stella-Hxy** [comment]
How can I get the Makeup-wild dataset for testing？I can‘t find the corresponding link. Thanks!

**Comment by wtjiang98** [comment]
The download link is updated
