### ISSUE TITLE
landmark and segments file 

### ISSUE THREAD

**Issue by back-js** [wtjiang98/PSGAN#24]
Hi!

Your project is interesting so I want to train more about the data.

But I have a question because I have no deep knowledge of this field.

If i want to train more data, Should I have to make landmark and segments? ( Is this a necessary file for training? )

And Is it right ? ( segs = segments )

Thanks !

**Comment by wzy0903** [comment]
Sorry to  disturb you. Did you solve this problem?

**Comment by ZziTaiLeo** [comment]
I want to know this, too.

**Comment by wtjiang98** [comment]
> Hi!
> 
> Your project is interesting so I want to train more about the data.
> 
> But I have a question because I have no deep knowledge of this field.
> 
> If i want to train more data, Should I have to make landmark and segments? ( Is this a necessary file for training? )
> 
> And Is it right ? ( segs = segments )
> 
> Thanks !

Yes, you should obtain the segs (i.e. parsing results of face) and landmarks. [This repo](https://github.com/zllrunning/face-parsing.PyTorch) and dlib are used in this project. You can try to make your own dataset.
