### ISSUE TITLE
Test result

### ISSUE THREAD

**Issue by pirate-zhang** [wtjiang98/PSGAN#27]
I tried to run the code for PSGAN, and when I tested it with the G.pth generated by training, the results were very bad.like this.It is quite different from the test results you provided.I don't know what's wrong, so I'm asking for your advice.Please reply to me when you have time. Thank you very much.

**Comment by wtjiang98** [comment]
> I tried to run the code for PSGAN, and when I tested it with the G.pth generated by training, the results were very bad.like this.It is quite different from the test results you provided.I don't know what's wrong, so I'm asking for your advice.Please reply to me when you have time. Thank you very much.

You can attach your results here, and open a new issue.

**Comment by pirate-zhang** [comment]
您好，我已收到您的邮件。谢谢！

**Comment by pirate-zhang** [comment]
您好，我已收到您的邮件。谢谢！
