### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by AragornKris** [wtjiang98/PSGAN#28]
Hello,
I use a RTX2080ti to train the dataset you provided and do not change any code, but an "CUDA out of memory" error  occurred in the program. Could you give some help? Thank you !

**Comment by PennyPeng369** [comment]
I met the same issue. I think the GPU memory required may be >= 12G. I havn't found any workable method to solve it.
Any thought of solution would be appreciated. Thanks.

**Comment by AragornKris** [comment]
> I met the same issue. I think the GPU memory required may be >= 12G. I havn't found any workable method to solve it.
> Any thought of solution would be appreciated. Thanks.

I delete part of the parallel calculation code(in solver.py from line125 to line134), it can work.

**Comment by AloneGu** [comment]
Replace all `64` with `32` of Generator.__init__ ( in net.py ), the max gpu memory usage is around 7500MiB, it goes well with my GTX 1070

**Comment by sq2001** [comment]
export CUDA_VISIBLE_DEVICES=0 before running python main.py
It seems parallel calculation needs the GPU memory >=12G.

**Comment by AragornKris** [comment]
这是来自QQ邮箱本人忙碌的回复
 
您好，我最近很忙，无法亲自回复您的邮件。我忙完后，会尽快给您回复。

**Comment by wtjiang98** [comment]
> Replace all `64` with `32` of `Generator.__init__` ( in net.py ), the max gpu memory usage is around 7500MiB, it goes well with my GTX 1070

That's a good idea. Just reduce the dimension of the bottlenecks.
