### ISSUE TITLE
Histogram loss on lip and eyes

### ISSUE THREAD

**Issue by CelineWang1027** [wtjiang98/PSGAN#29]
Hi, thanks for your wonderful works.
When I am trying to implement your code, I found that the histogram loss on lip and eyes are always 0. This issue leads to inaccuracy on makeup transfer of lipstick and eyeshadow. I tried but failed to find out the possible problem in codes. Can you do me a favor? I did not change codes in calculating histogram loss.
 
![G-A-eye-loss-his](https://user-images.githubusercontent.com/65447594/119922771-79e07c80-bfab-11eb-9125-c1f63eac9d13.png)
![G-A-lip-loss-his](https://user-images.githubusercontent.com/65447594/119922787-82d14e00-bfab-11eb-925d-996838925f93.png)

**Comment by Hong-Bo** [comment]
Encountered the same issue. Did you solve it? Thanks

**Comment by YongshengDong** [comment]
> Encountered the same issue. Did you solve it? Thanks

Have you solved it?

**Comment by Hong-Bo** [comment]
> > Encountered the same issue. Did you solve it? Thanks
> 
> Have you solved it?

Please simply just do not load the pretrained weights

**Comment by YongshengDong** [comment]
> > > Encountered the same issue. Did you solve it? Thanks
> > 
> > 
> > Have you solved it?
> 
> Please simply just do not load the pretrained weights

Hi,
   I train it without the pretrained weights, however the histogram loss on lip and eyes are still zero

**Comment by Hong-Bo** [comment]
> > > > Encountered the same issue. Did you solve it? Thanks
> > > 
> > > 
> > > Have you solved it?
> > 
> > 
> > Please simply just do not load the pretrained weights
> 
> Hi,
> I train it without the pretrained weights, however the histogram loss on lip and eyes are still zero

I solved this problem three weeks ago and could not remember details. Despite not loading the pretrained weights, there's something wrong about the makeup loss as my memory rewinds, a problem that I forgot to write down. I tackled the problem by visualizing the image results during and after Histogram matching. I bet you could solve the problem via visualizing intermediate results too.

**Comment by YongshengDong** [comment]
> > > > > Encountered the same issue. Did you solve it? Thanks
> > > > 
> > > > 
> > > > Have you solved it?
> > > 
> > > 
> > > Please simply just do not load the pretrained weights
> > 
> > 
> > Hi,
> > I train it without the pretrained weights, however the histogram loss on lip and eyes are still zero
> 
> I solved this problem three weeks ago and could not remember details. Despite not loading the pretrained weights, there's something wrong about the makeup loss as my memory rewinds, a problem that I forgot to write down. I tackled the problem by visualizing the image results during and after Histogram matching. I bet you could solve the problem via visualizing intermediate results too.

Could you share the makeup loss after you fixed it? Actually, I visualized the image after Histogram matching and found the result which before and after histogram_matching was same!  I am puzzled about it, do you have any ideas?

**Comment by Hong-Bo** [comment]
> > > > > > Encountered the same issue. Did you solve it? Thanks
> > > > > 
> > > > > 
> > > > > Have you solved it?
> > > > 
> > > > 
> > > > Please simply just do not load the pretrained weights
> > > 
> > > 
> > > Hi,
> > > I train it without the pretrained weights, however the histogram loss on lip and eyes are still zero
> > 
> > 
> > I solved this problem three weeks ago and could not remember details. Despite not loading the pretrained weights, there's something wrong about the makeup loss as my memory rewinds, a problem that I forgot to write down. I tackled the problem by visualizing the image results during and after Histogram matching. I bet you could solve the problem via visualizing intermediate results too.
> 
> Could you share the makeup loss after you fixed it? Actually, I visualized the image after Histogram matching and found the result which before and after histogram_matching was same! I am puzzled about it, do you have any ideas?

I made tons of modification locally. It's a little difficult for me to tell which modification solved the problem. Nonetheless, a cross comparison with the HEAD might point answer to line 26 and 29 in HistogramLoss class. You can try to remove the unsqueeze action in these two lines.

**Comment by YongshengDong** [comment]
> > > > > > > Encountered the same issue. Did you solve it? Thanks
> > > > > > 
> > > > > > 
> > > > > > Have you solved it?
> > > > > 
> > > > > 
> > > > > Please simply just do not load the pretrained weights
> > > > 
> > > > 
> > > > Hi,
> > > > I train it without the pretrained weights, however the histogram loss on lip and eyes are still zero
> > > 
> > > 
> > > I solved this problem three weeks ago and could not remember details. Despite not loading the pretrained weights, there's something wrong about the makeup loss as my memory rewinds, a problem that I forgot to write down. I tackled the problem by visualizing the image results during and after Histogram matching. I bet you could solve the problem via visualizing intermediate results too.
> > 
> > 
> > Could you share the makeup loss after you fixed it? Actually, I visualized the image after Histogram matching and found the result which before and after histogram_matching was same! I am puzzled about it, do you have any ideas?
> 
> I made tons of modification locally. It's a little difficult for me to tell which modification solved the problem. Nonetheless, a cross comparison with the HEAD might point answer to line 26 and 29 in HistogramLoss class. You can try to remove the unsqueeze action in these two lines.

Solve it! Thanks a lot!

**Comment by CelineWang1027** [comment]
solved.

**Comment by zimenglan-sysu-512** [comment]
@CelineWang1027 how did u solve it?
