### ISSUE TITLE
about 'affine' param in InstanceNorm2d

### ISSUE THREAD

**Issue by YongshengDong** [wtjiang98/PSGAN#31]
Hi,
   The affine in nn.InstanceNorm2d make me confused, why some use True and some use False in Generator?

**Comment by wtjiang98** [comment]
> Hi, The affine in nn.InstanceNorm2d make me confused, why some use True and some use False in Generator?

You can refer to the paper for this detail. If you use the gamma and beta generated by AMM, you should set the affine in nn.InstanceNorm2d to be False.
