### ISSUE TITLE
white spots in the generated image

### ISSUE THREAD

**Issue by melody-rain** [wtjiang98/PSGAN#32]
![49_2048_fake](https://user-images.githubusercontent.com/2832736/131277962-a6fd75cf-e5d3-4789-9d97-7e9f4f62ad6e.jpg)

When training with the code of this repo, my generated images always have white spots. Does anyone have the similar results? And how to avoid it?

Thanks

**Comment by PennyPeng369** [comment]
I meet similar problem in other GAN model. My generated images always have green spots at same location of face. I have no idea about the reason...
Any suggestion wil be appreciated. Thanks.

**Comment by melody-rain** [comment]
@PennyPeng369 @wanzysky yes according to stylegan2, replacing all conv2d with demodulated conv2d, the white spots disappear in my experiments. But I am wandering why the author’s released model has no such a problem.

**Comment by wtjiang98** [comment]
> @PennyPeng369 @wanzysky yes according to stylegan2, replacing all conv2d with demodulated conv2d, the white spots disappear in my experiments. But I am wandering why the author’s released model has no such a problem.

Yes, the white spot is caused by instance normalization. Replacing the original conv2d could be a good idea.
