### ISSUE TITLE
Download makeup-wild Dataset

### ISSUE THREAD

**Issue by jktee** [wtjiang98/PSGAN#34]
Hi, I tried to get the Makeup-wild dataset, but the link shows that the file was not found, how can I get it again?

**Comment by longwayfather** [comment]
I have the same problem...How did you get that dataset

**Comment by Stella-Hxy** [comment]
@jktee 
You closed the question, how did you get the Makeup-wild dataset? Thanks!

**Comment by ZziTaiLeo** [comment]
Hi，I have same questions,too.  Where did you found the dataset?  Could you tell us how to get  that?  Thanks!
