### ISSUE TITLE
[When you plan to commit training code]

### ISSUE THREAD

**Issue by vuthede** [wtjiang98/PSGAN#5]
Hello @wtjiang98,
Thanks alot for implementing PSGAN. I just wonder when you plan to commit the training code.
I am just very new at GAN in general but  I am quite interested in that and plan to implement the training code but I think it will take me along time to finish coding and more importantly make it work as in the paper. But if you will release the training code soon, it is very useful for me to know.
Thanks and sorry because it is not actually an issue

**Comment by wtjiang98** [comment]
It will takes at least one month since there are some issues to be solved. 
I am sorry about that.
