### ISSUE TITLE
A forked implementation with training code and multiple GPU support

### ISSUE THREAD

**Issue by wanzysky** [wtjiang98/PSGAN#9]
I have optimized the code for training and GPU support in https://github.com/wanzysky/PSGAN.

I'm not sure whether a pull request is encouraged.

**Comment by wtjiang98** [comment]
> I have optimized the code for training and GPU support in https://github.com/wanzysky/PSGAN.
> 
> I'm not sure whether a pull request is encouraged.

Sure!
Thanks for your contribution! I have sent you an email.
